stages:
  - build
  - test
  - analyse
  - build-image

build-job:
  stage: build
  script:
    - docker build -t userservice-server .

test-job:
  stage: test
  script:
    - ./mvnw test

analyse-job:
  stage: analyse
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - ./mvnw sonar:sonar
      -Dsonar.projectKey=userservice
      -Dsonar.projectName=userservice
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONARQUBE_TOKEN}

build-image-job:
  stage: build-image
  script:
    - docker compose up -d