stages:
  - build
  - test
  - analyse
  - build-image

build-job:
  stage: build
  script:
    - docker build -t userservice-server .

test-job:
  stage: test
  script:
    - ./mvnw test

analyse-job:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:4.8
    entrypoint: [ "" ]
    variables:
      GIT_STRATEGY: clone
      GIT_DEPTH: 0
    rules:
      - if: $CI_PIPELINE_SOURCE != "schedule"
    needs: [ build ]
    script:
      - sonar-scanner

build-image-job:
  stage: build-image
  script:
    - docker compose up -d