spring:
  application:
    name: userservice
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/userservice_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none

