spring:
  application:
    name: userservice
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice_db
    username: postgres
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none