name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build application
        run: |
          chmod +x ./mvnw
          ./mvnw clean compile -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-classes
          path: target/classes/
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        java-version: [17]

    services:
      docker:
        image: docker:24.0.7-dind
        options: --dns 8.8.8.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-classes
          path: target/classes/

      - name: Set up Docker
        run: |
          sudo groupadd docker || true
          sudo usermod -aG docker $USER
          newgrp docker
          docker version

      - name: Run tests
        env:
          DOCKER_HOST: tcp://docker:2375
          DOCKER_TLS_CERTDIR: ""
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: |
          chmod +x ./mvnw
          ./mvnw test -Dtestcontainers.reuse.enable=true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports/
            target/site/jacoco/
          retention-days: 30

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml

  analyse:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        java-version: [17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./

      - name: SonarQube analysis
        env:
          SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        run: |
          chmod +x ./mvnw
#          ./mvnw sonar:sonar \
#            -Dsonar.projectKey=Dangerinchik_userservice \
#            -Dsonar.projectName=dangerinchik \
#            -Dsonar.host.url=$SONARQUBE_URL \
#            -Dsonar.login=$SONARQUBE_TOKEN \
#            -Dsonar.organization=dangerinchik \
#            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.token=$SONARQUBE_TOKEN \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=dangerinchik \
            -Dsonar.projectKey=Dangerinchik-userservice

  package:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        java-version: [17]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build package
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: application-package
          path: target/*.jar
          retention-days: 7